import type { NextPage } from "next";
import Head from "next/head";
import s from "../styles/Home.module.css";
import useSWRInfinite, { SWRInfiniteKeyLoader } from "swr/infinite";
import ky from "ky";

const HomeContent = () => {
  const { data, isLoading, error } = useSWRInfinite(
    () => "pokemons",
    () =>
      ky.get("https://pokeapi.co/api/v2/pokemon?limit=100000&offset=0").json(),
  );

  if (!data && isLoading) return <div>loading...</div>;

  if (error) return <div>error</div>;

  return <pre>{JSON.stringify(data, null, 2)}</pre>;
};

const Home: NextPage = () => {
  return (
    <div className={s.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <HomeContent />
      </main>
    </div>
  );
};

export default Home;